@startuml
hide footbox

participant "Zorgviewer-Back-end" as zv
participant "<<Ontsluiten bronsysteem>>\nIRIS" as obron
participant "<<Bronsysteem>>\nEPIC" as bron

zv->obron: gegevensverzoek (FHIR request)
activate zv
activate obron
obron->bron: Consent call uitvoeren voor de gewenste patient\n""<epic-fhir-base>/Consent?category=http://loinc.org|59284-0&patient=<patient_fhir_id>""
note right obron
  "Toestemming uitwisselen dossier" consent is active als:
  ""Consent.coding[0] = urn:oid:1.2.840.114350.1.13.3.7.4.686783.100#201047""
  en datum van vandaag valt in ""Consent.period"" en ""Consent.active = #active""
end note
alt geen active consent
  obron-->zv: lege Bundle
else active consent
  obron->bron: doorsturen gegevensverzoek (FHIR request)
  bron-->obron: results Bundle
  obron-->zv: results Bundle
end

deactivate obron
deactivate zv

@enduml