@startmindmap
* DataSets
** [[https://informatiestandaarden.nictiz.nl/wiki/MedMij:V2020.01/OntwerpPDFA PDF/a]]
***_ Correspondentie
** [[https://informatiestandaarden.nictiz.nl/wiki/MedMij:V2020.01/OntwerpBGZ_2017 Basisgegevensset Zorg]] (BgZ)
*** Problemen (incl. diagnosen)
*** Verrichtingen
*** Behandelaanwijzingen
*** Wilsverklaringen
*** Laboratoriumuitslagen
*** Alerts / Waarschuwingen
*** Allergieen en intoleranties
*** Medicatiegegevens
****_ Medicatieafspraken
****_ Medicatie Gebruik
** Advanced Care Planning (ACP)
***_ Behandelaanwijzingen / wensen
** [[https://informatiestandaarden.nictiz.nl/wiki/Landingspagina_Verpleegkundige_Zorg Verpleegkundige eOverdracht]]
***_ Minimale eOverdracht (MeO) 
@endmindmap