@startuml

skinparam nodesep 1
skinparam ranksep 1

package "Zorgviewer" {
 (Patient\nbanner)
 (Weergave\ngegevens)
 (Sorteren)
 (Conflicten\nattenderen)
 (Ontdubbelen\ngegevens)
 (Filtering obv\nBehandelplan)
}

package "Zorgviewer Host" {
 (Opstart\nZorgviewer)
 (Stelt\nidentity vast)
 (Controle\nbehandelrelatie)
 (Patient\nselectie)
 (Zorgverlener\ngegevens)
 (Zorgverlener\nrollen)
}

cloud {
 package "Behandelplan" {
  (Behandelplannen\nadhv diagnose)
  (Relevante gegevens\nadhv zorgpad)
  (Relevante gegevens\nadhv rol)
 }
 package "Toestemming & Patientindex" {
  (Toegestane\nbronsystemen patient)
  (Bronsystemen\nendpoints)
 }
}

@enduml