@startuml

title "Functionaliteiten per bouwblok"

'left to right direction


package "Zorgviewer" {
 (Filtering obv Zorgpad, sorteren)
 (Conflicten attenderen)
 (Zorgpad weergave)
 (Patient banner)
 (Weergave gegevens)
}

package "Epic, Chipsoft, Zorgviewer Los" <<Zorgviewer Host>> {
 (Stelt identity vast)
 (Patient selectie)
 (Controle behandelrelatie)
 (Opstart Zorgviewer)
}

cloud {
 package [Behandelplan] {
  (Behandelplannen adhv diagnose)
  (Relevante gegevens adhv zorgpad)
  (Relevante gegevens adhv rol)
 }
 package [MITZ] <<Toestemming & Patientindex>> {
  (Toegestane bronnen patient)
 }
 package [ZorgAB] <<Zorgverlener Registry>> {
  (Zorgverlener rollen)
  (Zorgverlener gegevens)
  (Bronnen endpoints)
 }
}



@enduml