@startuml 

state "Concept" as concept
state "(1) WG review" as WGreview
state "(2) PO review" as POreview

concept : werken in master branch [[https://build.fhir.org/ig/RIVO-Noord/zorgviewer-ig/ CI Build]]
WGreview : werkgroepen IG en Bouw review [[https://vdzel.home.xs4all.nl/zorgviewer-ig/branches/ laatste tag]]
POreview : product owner review [[https://vdzel.home.xs4all.nl/zorgviewer-ig/ release]]

[*] --> concept : new minor\n0.m.0
concept -[bold]-> WGreview : tag release
WGreview -[dashed]-> concept : [comments]\nnew revision\n0.m.r+1 
WGreview -[bold]-> POreview : [no comments]\npublish
POreview -[dashed]-> concept : [comments]\nnew revision\n0.m.r+1 
POreview -[bold]-> publicatie : [no comments]\nrelease\n0.m.r
publicatie --> [*] : volgende iteratie\n0.m+1.0
publicatie -[dotted]-> concept : [comments]\nop laatste revision

state publicatie {
   state "(3) Breed review" as BRreview
   BRreview : breed review o.a. RIVO Architecten
   state release
  }

@enduml