@startuml
hide footbox
autonumber

actor Zorgverlener
box "Zorgaanbieder eigen systeem"
  participant "Zorgviewer\nHost" as Host
  participant "Eigen\nbronsysteem" as EBron
  participant Authenticatie
end box

!pragma teoz true
box "Zorgviewer Netwerk" #LightGreen
  box "Zorgviewer" #SpringGreen
    participant "Zorgviewer\nFrontend\n(in Browser)" as ZVFE
    participant "Zorgviewer\nBackend" as ZVBE
  end box
  participant "Toestemming\n~MITZ" as Toestemming
  participant Adressering
end box

box "Andere zorgaanbieder bronsysteem\n(meerdere)"
  participant "Ontsluiten\nbronsysteem" as AOBron
  participant "Bronsysteem" as ABron
end box

note over Host
  CHECK: Zorgaanbieder is deelnermer RIVO-Noord
  CHECK: Zorgaanbieder staat in [[https://www.nen.nl/certificatie-en-keurmerken-nen-7510 NEN 7510 register]]
end note

== Start Zorgviewer Host ==

Zorgverlener->Host ** : start EPD
activate Zorgverlener
activate Host
Zorgverlener->Host: inloggen met lokale identiteit
Host->Authenticatie
activate Authenticatie
Authenticatie ->x Authenticatie
note left
  CHECK: authenticatie
end note
deactivate Authenticatie
Zorgverlener->Host: selecteer patient
Host ->x Host
note left
  CHECK: behandelrelatie
end note

...

== Start Zorgviewer ==

Zorgverlener->Host: start Zorgviewer
Host ->x Host
note left
  PRE-CONDITIE: op basis van security context
    "knop" wel of niet beschikbaar
end note
Host->ZVFE ** : start met context
activate ZVFE
ZVFE ->x ZVFE
note right
  CHECK: whitelist
  CHECK: token validatie
end note
ZVFE<->Authenticatie: authenticatie handshake\nOAuth2/ClientID
note left
  CHECK: applicatie
end note
destroy Authenticatie

== Huidige patient en gebruiker ==

group (OPTIONEEL) als niet al in context
  ZVFE-->EBron: (OPTIONEEL) opvragen huidige gebruiker\nen patient details
  note left
    CHECK: access token
  end note
  destroy EBron
end
ZVFE->ZVFE: toon gebruiker en patient\nidentiteit details

== Patient dossier ==

ZVFE->ZVBE: opvragen gegevens
activate ZVBE
ZVBE->Toestemming: vraag patient toestemmingen op
note right
  Wordt MITZ Open autorisatievraag\nals dit in de regio in productie is
end note
destroy Toestemming
ZVBE->Adressering: vraag endpoints (lokaties) op van organizaties\nobv de toestemmingen
note right
  binnen besloten Zorgviewer netwerk
end note
destroy Adressering
loop Voor ieder endpoint
  ZVBE->AOBron: opvragen gegevens
  activate AOBron
  AOBron ->x AOBron
  note left
    CHECK: ip/ACL
  end note
  AOBron->ABron: opvragen gegevens
  activate ABron
  ABron ->x ABron
  note left
    CHECK: ip/ACL
    CHECK: backend token
    CHECK: client certificate
  end note
  group Check toestemming OPTIES
    note over AOBron
      Als MITZ in productie is in de regio wordt dit de Gesloten autorisatie vraag 
      vanuit bron (b) of vanuit ontsluiten bronsysteem (b) als de bron dit niet zelf kan.
    end note
    AOBron->ABron: (a) Check locale toestemming
    ABron->Toestemming: (b) Check toestemming
  end
  ABron ->x ABron
  note left
    CHECK: vraag gesteld zonder MITZ toestemming
  end note
  ABron-->AOBron: gegevens
  deactivate ABron
  AOBron-->ZVBE: gegevens
  deactivate AOBron
end
ZVBE-->ZVFE: toon geaggregeerde gegevens
deactivate ZVBE
deactivate ZVFE

@enduml