@startsalt
skinparam Backgroundcolor white
{+
    {}
    == <&eyedropper> Medicatie gebruik
    {}
    {T#
    **Bron** | **Datum** | **Medicatie** | **Toedieningsweg** | **Instructies** | **Categorie**
    <&medical-cross> UMCG | 15-feb-2022 | nitroprusside 1mg/ml spuit voor pomp | Intraveneus | continu 1 microg/min intraveneus toedienen | Community 
    . | . | generate rows from examples
    }
    {}
}
@endsalt
