@startuml ViewDefinition-MedicationStatement
:
== Medicatie Gebruik
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |
| meta...| medicationReference...| dosage...| dosage...| dateAsserted...| category...|
| string | string | string | string | dateTime | string |
| nvt | ProductUsed | InstructionsForUse\n /RouteOfAdministration | InstructionsForUse\n /Description | MedicationUseDateTime | nvt |
;
@enduml