@startuml ViewDefinition-Behandelaanwijzingen
:
== Behandelaanwijzingen
|= Bron |= Category |= Datum |= Behandeling |= Behandeling toegestaan |= Beperkingen |= Geverifieerd bij |= +Toelichting |= (status) |
| Chipsoft | Treatment instructions | 2022-09-30T10:33:00+02:00 | Artificial respiration (procedure) | Ja, maar met beperkingen |  |  |  | active |
| Epic | Advance Directive & Vastgelegd | 2022-03-22T12:45:21Z | kunstmatige beademing (verrichting) | Ja, maar met beperkingen |  | patiënt (persoon) |  | active |
| Nexus | Behandelingsinstructies (artefact opnemen) | 2023-05-05 | Kunstmatige beademing | Behandeling niet toegestaan en/of wenselijk |  |  | testje | active |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml