@startuml ViewDefinition-Immunization
:
== undefined
|= Bron |= Datum |= Product |= Toelichting |
|<back:yellow> //nvt//\n<back:lightgreen> //string// |<back:yellow> //VaccinatieDatum//\n<back:lightgreen> //dateTime// |<back:yellow> //ProductCode//\n<back:lightgreen> //string// |<back:yellow> //Toelichting//\n<back:lightgreen> //string// |
| |

<color:gray>//Column fhirpaths://
<color:gray>//1. meta.extension('http:~//hl7.org/fhir/4.0/StructureDefinition/extension-Meta.source').valueUri//
<color:gray>//2. date//
<color:gray>//3. iif(exists(vaccineCode.text),vaccineCode.text,vaccineCode.coding.display)//
<color:gray>//4. note.text//
;
@enduml