@startuml ViewDefinition-MedicationRequest
:
== Medicatie Afspraken
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |
|<back:yellow> //nvt//\n<back:lightgreen> //string// |<back:yellow> //Afgesprokengeneesmiddel//\n<back:lightgreen> //string// |<back:yellow> //Gebruiksinstructie\n<back:yellow> ///Toedieningsweg//\n<back:lightgreen> //string// |<back:yellow> //Gebruiksinstructie\n<back:yellow> ///Omschrijving//\n<back:lightgreen> //string// |<back:yellow> //MedicatieafspraakDatumTijd//\n<back:lightgreen> //dateTime// |<back:yellow> //nvt//\n<back:lightgreen> //string// |
| |

<color:gray>//Column fhirpaths://
<color:gray>//1. meta.extension('http:~//hl7.org/fhir/4.0/StructureDefinition/extension-Meta.source').valueUri//
<color:gray>//2. medicationReference.display//
<color:gray>//3. dosageInstruction.route.text.toString()//
<color:gray>//4. dosageInstruction.text.toString()//
<color:gray>//5. authoredOn//
<color:gray>//6. category.text//
;
@enduml