@startuml ViewDefinition-MedicationStatement
:
== Medicatie Gebruik
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml