@startuml ViewDefinition-Wilsbeschikkingen
:
== Wilsbeschikkingen
|= Bron |= Datum |= Type |
| Chipsoft | 2018-04-09 | Patiëntinformatie - Wilsbeschikkingen |
| Nexus | 2018-04-09 |  |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml