@startuml ViewDefinition-AllergyIntolerance
:
== Allergieen en intoleranties
|= Bron |= Datum |= Stof |= Toelichting |= Categorie |= CategorieCS |= Ernst(1) |= Ernst(1)CS |= Ernst(2) |= Reacties |= Status |= StatusCS |= (VStatus) |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml