@startuml ViewDefinition-DocumentReference
:
== Correspondentie
|= Bron |= Datum |= Type |= Class |= Beschrijving |= Auteur |= Specialisme |= (MimeType - voor filteren op pdf) |
| meta... | iif(exists(context... | iif(type... | iif(class... | iif(exists(description),description,content... | author... | iif(context... | content |
| string |  |  |  |  |  |  |  |
| nvt |  |  |  |  |  |  |  |
| |
| Chipsoft | 2022-05-11T22:00:00+00:00 | 51852-2 | 51852-2 | test.pdf |  | 394802001 | application/pdf |
| Epic | 2021-12-15T09:36:00Z | Patiëntenbrief | Correspondence | Patiëntenbrief | G Boer | KGA - Genetica | application/pdf |
;
@enduml