@startuml ViewDefinition-MedicationRequest
:
== Medicatie Afspraken
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |
| meta...| medicationReference...| dosageInstruction...| dosageInstruction...| authoredOn...| category...|
| string | string | string | string | dateTime | string |
| nvt | AgreedMedicine\n /Medication | InstructionsForUse\n /RouteOfAdministration | InstructionsForUse\n /Description | MedicationAgreementDateTime | nvt |
;
@enduml