@startuml ViewDefinition-MedicationStatement
:
== Medicatie Gebruik
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |
|<back:yellow> meta... |<back:yellow> medicationReference.display |<back:yellow> dosage.route.text |<back:yellow> dosage.text |<back:yellow> dateAsserted |<back:yellow> category.text |
|<back:yellow> string |<back:yellow> string |<back:yellow> string |<back:yellow> string |<back:yellow> dateTime |<back:yellow> string |
|<back:yellow> nvt |<back:yellow> ProductUsed |<back:yellow> InstructionsForUse\n /RouteOfAdministration |<back:yellow> InstructionsForUse\n /Description |<back:yellow> MedicationUseDateTime |<back:yellow> nvt |
| |
;
@enduml