@startuml ViewDefinition-Immunization
:
== undefined
|= Bron |= Datum |= Product |= Toelichting |
|<back:yellow> meta... |<back:yellow> date |<back:yellow> iif(exists(vaccineCode.text),vaccineCode.text,vacc... |<back:yellow> note.text |
|<back:yellow> string |<back:yellow> dateTime |<back:yellow> string |<back:yellow> string |
|<back:yellow> nvt |<back:yellow> VaccinatieDatum |<back:yellow> ProductCode |<back:yellow> Toelichting |
| |
;
@enduml