@startuml ViewDefinition-Behandelaanwijzingen
:
== Behandelaanwijzingen
|= Bron |= Category |= Datum |= Behandeling |= Behandeling toegestaan |= Beperkingen |= Geverifieerd bij |= (status) |
|<back:yellow> //nvt//\n<back:lightgreen> //string// |<back:yellow> \n |<back:yellow> \n |<back:yellow> \n |<back:yellow> \n |<back:yellow> \n |<back:yellow> \n |<back:yellow> \n |
| |

<color:gray>//Column fhirpaths://
<color:gray>//1. meta.extension('http:~//hl7.org/fhir/4.0/StructureDefinition/extension-Meta.source').valueUri//
<color:gray>//2. category.coding.display.join(' & ')//
<color:gray>//3. period.start//
<color:gray>//4. extension('http:~//nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective-Treatment').valueCodeableConcept.coding[0].display//
<color:gray>//5. modifierExtension.where(url='http:~//nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective-TreatmentPermitted').valueCodeableConcept.coding.display//
<color:gray>//6. except.extension('http:~//nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective-Restrictions').value//
<color:gray>//7. extension('http:~//nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective-Verification').extension('VerifiedWith').valueCodeableConcept.text.join(' & ')//
<color:gray>//8. status//
;
@enduml