@startuml ViewDefinition-DocumentReference
:
== Correspondentie
|= Bron |= Datum |= Type |= Class |= Beschrijving |= Auteur |= Specialisme |= (MimeType - voor filteren op pdf) |
| meta...| iif(exists(context...| iif(type...| iif(class...| iif(exists(description),description,content...| author...| iif(context...| content...|
| string |  |  |  |  |  |  |  |
| nvt ||||||||
;
@enduml