@startuml ViewDefinition-Condition
:
== Problemen (incl. diagnosen)
|= Bron |= Datum |= Diagnose |= +Diagnose |= +Toelichting |= (regelkleur) |
|<back:yellow> meta... |<back:yellow> iif(exists(onsetPeriod),onsetPeriod.start,onsetDat... |<back:yellow> code.text |<back:yellow> code.coding[0].system+'#'+code.coding[0].code+' '+... |<back:yellow> note.text |<back:yellow> clinicalStatus |
|<back:yellow> string |<back:yellow> Period,dateTime |<back:yellow> string |<back:yellow> string |<back:yellow> string |<back:yellow> code |
|<back:yellow> nvt |<back:yellow> ProbleemBeginDatum |<back:yellow> ProbleemNaam |<back:yellow> ProbleemNaam |<back:yellow> Toelichting |<back:yellow> ProbleemStatus |
| Chipsoft | 2001-01-01 | fractuur van pols | http://hl7.org/fhir/v3/NullFlavor#OTH other | Gevallen op kunstijsbaan. | active |
| Epic-note | 2023-02-23 | posttraumatische stressstoornis (incl. de posttraumatische-stressstoornis bij ki... | http://hl7.org/fhir/sid/icd-10-nl#F43.1  | 2022-02: ziekte van Crohn\n 2021-07: Complicatie ANPY infectie lokaal\n 2021-03:... | active |
| Epic | 2012-08-16 | fractuur van onderste extremiteit | http://hl7.org/fhir/sid/icd-10-nl#T12.0  |  | active |
| Nexus | 2001 |  | http://snomed.info/sct#31641000146105 fractuur van pols | Gevallen op kunstijsbaan | inactive |
| |
;
@enduml