@startuml ViewDefinition-Behandelaanwijzingen
:
== Behandelaanwijzingen
|= Bron |= Category |= Datum |= Behandeling |= Behandeling toegestaan |= Beperkingen |= Geverifieerd bij |= (status) |
|<back:yellow> meta... |<back:yellow> category.coding.display.join(' & ') |<back:yellow> period.start |<back:yellow> extension('http://nictiz.nl/fhir/StructureDefiniti... |<back:yellow> modifierExtension.where(url='http://nictiz.nl/fhir... |<back:yellow> except.extension('http://nictiz.nl/fhir/StructureD... |<back:yellow> extension('http://nictiz.nl/fhir/StructureDefiniti... |<back:yellow> status |
|<back:yellow> string |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |
|<back:yellow> nvt |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |<back:yellow>  |
| |
;
@enduml