@startuml ViewDefinition-Wilsbeschikkingen
:
== Wilsbeschikkingen
|= Bron |= Datum |= Type |
| Chipsoft | 2018-04-09 | Patiëntinformatie - Wilsbeschikkingen |
| Epic | 2022-06-30T14:02:08Z | Niet reanimeren verklaring |
| Nexus | 2018-04-09 |  |
| Epic | 2021-10-12T10:55:32Z | Niet reanimeren verklaring |
| Chipsoft |  |  |
| Epic | 2022-03-22T12:45:21Z |  |
| Nexus | 2018-04-09T11:40:11+02:00 |  |
| Topicus |  |  |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml