@startuml ViewDefinition-Medicatiegegevens
:
== Medicatie Gebruik en Afspraken
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |= +Type |
| meta...| medicationReference...| dosageInstruction...| dosageInstruction...| authoredOn...| category...| 'voorgeschreven'...|
| string | string | string | string | dateTime | string |  |
| nvt | AgreedMedicine\n /Medication | InstructionsForUse\n /RouteOfAdministration | InstructionsForUse\n /Description | MedicationAgreementDateTime | nvt ||
|= Bron |= Medicatie |= Toedieningsweg |= Dosering & Instructies |= Datum |= +Categorie |= +Type |
| meta...| medicationReference...| dosage...| dosage...| dateAsserted...| category...| 'huidig'...|
| string | string | string | string | dateTime | string |  |
| nvt | ProductUsed | InstructionsForUse\n /RouteOfAdministration | InstructionsForUse\n /Description | MedicationUseDateTime | nvt ||
;
@enduml