@startuml ViewDefinition-Procedure
:
== Verrichtingen
|= Bron |= Datum |= Verrichting |= Locatie |= Uitgevoerd door |= +Verrichtingcode |= +Lateraliteit |
| meta...| performedPeriod...| iif(exists(code...| location...| performer...| code...| bodySite...|
| string | dateTime | string | string | string | string | string |
| nvt | VerrichtingBeginDatum | VerrichtingType | Locatie::Zorgaanbieder | Uitvoerder | VerrichtingType | ProbleemLateraliteit |
;
@enduml