@startuml ViewDefinition-Condition
:
== Problemen (incl. diagnosen)
|= Bron |= Datum |= Diagnose |= +Diagnose |= +Toelichting |= (regelkleur) |
| meta...| iif(exists(onsetPeriod),onsetPeriod...| code...| code...| note...| clinicalStatus...|
| string | Period,dateTime | string | string | string | code |
| nvt | ProbleemBeginDatum | ProbleemNaam | ProbleemNaam | Toelichting | ProbleemStatus |
;
@enduml