@startuml ViewDefinition-Wilsbeschikkingen
:
== Wilsbeschikkingen
|= Bron |= Datum |= Type |
| Chipsoft | 9-4-2018 | Patiëntinformatie - Wilsbeschikkingen |
| Nexus | 9-4-2018 |  |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml