@startuml ViewDefinition-Immunization
:
== undefined
|= Bron |= Datum |= Product |= Toelichting |
| |

//Legenda//
//+Kolom - in de uitklap//
//(Kolom) - gebruikt voor formatting of verbergen//
;
@enduml