@startuml

cloud "cloud" {
 [Zorgviewer]
 [Behandelplan]
 [MITZ] <<Toestemming\n& Patientindex>>
 [ZorgAB] <<Zorgverlener\nRegistry>>
}

node "UMCG Epic" {
 [Hyperspace] <<Zorgviewer\nHost>>
 [Epic Auth] <<Authenticatie>>
 [IRIS] <<Bronsysteem\nontsluiting>>
 [Epic] <<Bronsysteem\n& Logging>>
 [Hyperspace]-->[Epic]
 [IRIS]-->[Epic]
 [Epic Auth]-->[Epic]
}

node "Chipsoft ziekenhuis" {
 [HiX] <<Zorgviewer Host\n& Logging\n& Bronsysteem>>
 [Zorgplatform\nAuth] <<Authenticatie>>
 [Zorgplatform] <<Bronsysteem\nontsluiting>>
 [Zorgplatform]->[HiX]
}

node "Zorgviewer Los" {
 [ZV Los] <<Zorgviewer\nHost>>
 [ZV Los Auth] <<Authenticatie>>
 note bottom of [ZV Los Auth] : Plus basis bron only Patient, Zorgverlener\nZorgviewerHostCapabilityStatement
}

[Hyperspace]-u->[Zorgviewer] :  1. opstart
[HiX]-u->[Zorgviewer] : 1. opstart
[ZV Los]-u->[Zorgviewer] : 1. opstart
[Zorgviewer]-d->[Epic Auth] : 2a. wie?
[Zorgviewer]-d->[ZV Los Auth] : 2a. wie?
[Zorgviewer]-d->[Zorgplatform\nAuth] : 2a. wie?
[Zorgviewer]-u->[ZorgAB] : 2b. wie en waar details?
[Zorgviewer]-u->[MITZ] : 3. waar?
[Zorgviewer]->[Zorgplatform] : 4. bevragen
[Zorgviewer]->[IRIS] : 4. bevragen
[Zorgviewer]-u->[Behandelplan] : 5. filters

@enduml