@startuml
hide footbox
autonumber

actor Zorgverlener
participant Zorgviewer
participant Logging
participant Behandelplan
box "Andere zorgaanbieder"
participant "Bronsysteem ontsluiting" as Bron
participant Bronsysteem
end box

activate Zorgviewer
Zorgverlener->Zorgviewer: ..vervolg bepalen zorgaanbieders..
Zorgviewer->Logging: log gebeurtenis, zie [[StructureDefinition-AuditEvent.html AuditEvent]]
Zorgviewer->Behandelplan: Bepalen minimale dataset\n""<behandelplan-base>/PlanDefinition?name=BgZ2017""
note right Zorgviewer
  Eerst hard-coded "BgZ2017" behandelplan.
  Later obv (hoofd)diagnose(zorgpad) of rol/specialisme gebruiker.
end note
activate Behandelplan
Behandelplan-->Zorgviewer: Behandelplan\n""[[StructureDefinition-PlanDefinition.html PlanDefinition]]""
deactivate Behandelplan
loop voor iedere zorgaanbieder
  Zorgviewer->Zorgviewer: [[Endpoint-UMCG.html Bronsysteem ontsluiting endpoint]]
  activate Zorgviewer
  Zorgviewer->Bron : verkrijg ""patient_fhir_id"" adhv BSN\n""<bronsysteem-ontsluiting-base>/Patient?identifier=<BSN>""
  activate Bron
  Bron->Bronsysteem : verkrijgen access token (na discovery)\ninclusief zorgviewer user organisatie tbv logging
  note right Bron
    auth_token bij access token request:
    { "iss": "...",
      "sub": "...",
      "exp": "...",
      ...
      "subject_name": "Int Arts",
      "subject_role": [ 
          { 
            "system": "2.16.840.1.113883.6.96", 
            "code": "309343006", 
            "display": "Arts" 
          } 
        ],
      (optioneel) "subject_organization": "UMCG",
      "subject_organization_id": "urn:oid:2.16.840.1.113883.2.4.3.8",
      ... }    
  end note
  Bron->Bronsysteem : Patient request
  activate Bronsysteem
  Bronsysteem-->Bronsysteem: log request
  Bronsysteem-->Bron : Patient resource
  note right Bron
"meta": {
    "extension": [ {
        "url": "http://hl7.org/fhir/4.0/StructureDefinition/extension-Meta.source",
        "valueUri": "uri:oid:2.16.840.1.113883.2.4.3.8"
    } ]
}
- of -
via Patient.managingOrganization.identifier
  end note
  deactivate Bronsysteem
  Bron-->Zorgviewer : ""[[StructureDefinition-Patient.html Patient]]""
  deactivate Bron
  loop gegevensverzoeken
    Zorgviewer->Zorgviewer: formuleren gegevensverzoek(request) adhv Behandelplan Data Requirements\n""PlanDefinition.action[0].output[].type""\nen ""PlanDefinition.action[0].output[].codeFilter""
    activate Zorgviewer
    Zorgviewer->Bron: gegevensverzoek\n""<bronsysteem-ontsluiting-base>/<resource>?patient=<patient_fhir_id>&<filter>""
    activate Bron
    opt als token verlopen
      Bron->Bronsysteem : verkrijgen access token (dmv backend account)
    end opt
    Bron->Bronsysteem : gegevensverzoek (per zib) met access token
    note right Bron
        header "X-Request-ID/AORTA-ID" meesturen
        zie [[https://nova.epic.com/Search.aspx?CstID=2#SearchTerm=818072 Epic Nova]]
    end note
    activate Bronsysteem
    Bronsysteem-->Bronsysteem: log request
    Bronsysteem->Bron: fhir resources (Bundle) bij de zib
    deactivate Bronsysteem
    Bron->Bron: Toevoegen meta-tag voor deze bron\nadhv Patient.managingOrganization of geconfigureerd adhv [[CodeSystem-bronsysteem-zorgaanbieder.html bronsysteem-zorgaanbieder]].
    note right Bron
"meta": {
    "extension": [ {
        "url": "http://hl7.org/fhir/4.0/StructureDefinition/extension-Meta.source",
        "valueUri": "uri:oid:2.16.840.1.113883.2.4.3.8"
    } ]
}
    end note
    Bron-->Zorgviewer: fhir resources (Bundle) bij de zib
    deactivate Bron
    deactivate Zorgviewer
    Zorgviewer->Zorgviewer: **TOEKOMST**: ontdubbelen en conflicten detectie
    note right of Zorgviewer
      Zorgviewer invulling van [[https://informatiestandaarden.nictiz.nl/wiki/BgZ:V1.0_BgZ_MSZ_Informatiestandaard BgZ]] 
      paragrafen 3.2.9.1 Ontdubbelen en 3.2.9.2 Duplicaatdetectie
    end note
  end
  deactivate Zorgviewer
end

Zorgviewer->Zorgviewer: toon gegevens
Zorgviewer-->Zorgverlener

@enduml
