@startuml
hide footbox
autonumber

actor Zorgverlener
box "Eigen zorgaanbieder"
participant "Zorgviewer Host" as Host
participant Authenticatie
end box
participant Zorgviewer
participant "Zorgverlener Directory" as ZorgverlenerDirectory

Zorgverlener->Host: start EPD
Zorgverlener->Host: inloggen met lokale identiteit
Zorgverlener->Host: selecteer patient
Zorgverlener->Host: start Zorgviewer
Host->Host: Configureer opstart parameters als context (patientid, practisionerid) (Epic FDI)
Host->Zorgviewer: start met context dmv smart-on-fhir \n""https://tst.zorgviewer.nl/application/launch""
note left Zorgviewer
 Oud Context is iig zorgviewer-host-base, access token, gebruiker_fhir_id, patient_fhir_id \n
 Context is gebruiker_fhir_id (id_token) en patient_fhir_id (patient)
end note

activate Zorgviewer
Zorgviewer->Host: Opvragen (lokale) gebruiker gegevens adhv gebruikerid\n""<zorgviewer-host-base>/Practitioner/<gebruiker_fhir_id>""\n""<zorgviewer-host-base>/PractitionerRole?practitioner=<gebruiker_fhir_id>""
Host-->Zorgviewer: ""[[StructureDefinition-Practitioner.html Practitioner]]""\n""[[StructureDefinition-PractitionerRole.html PractitionerRole]]""
note right Zorgviewer
    obv AGB-Z of ziekenhuis van de gebruiker via signing van token
end note
Zorgviewer->Zorgviewer++: CHECK Autorisatie/whitelist om Zorgviewer te starten
destroy Zorgviewer

' ZORB-AB Implementatiehandleiding 2.8 paragraaf 4.7
Zorgviewer->ZorgverlenerDirectory: LATER: Opvragen (landelijke) gebruiker gegevens adhv external identifier\n""<zorg-ab-base>/Practitioner/?identifier=<agb-z>""\n""<zorg-ab-base>/PractitionerRole?practitioner.identifier=http://fhir.nl/fhir/NamingSystem/agb-z|<agb-z>""
ZorgverlenerDirectory-->Zorgviewer: ""[[StructureDefinition-Practitioner.html Practitioner]]"" volledige zorgverlener gegevens
note right Zorgviewer
  Inclusief specialisme, rollen e.d. zoals extern bekend met externe codering AGB/VEKTIZ
end note

Zorgviewer->Zorgviewer: LATER: kies rol (als meerdere, nodig voor de view)

Zorgviewer->Zorgviewer: Toon gebruiker gegevens

Zorgviewer->Host: opvragen patient gegevens (lokaal patientid)\n""<zorgviewer-host-base>/Patient/<patient_fhir_id>""
Host-->Zorgviewer: ""[[StructureDefinition-Patient.html Patient]]"" (onder andere BSN voor verdere raadplegingen)
Zorgviewer->Zorgviewer: Toon patient

Zorgviewer->Zorgviewer: **ga naar de Bepalen zorgaanbieders sequence**

deactivate Zorgviewer

@enduml