@startuml
hide footbox
autonumber

actor Zorgverlener
participant Zorgviewer
box "Andere zorgaanbieder"
participant "Bronsysteem ontsluiting" as Bron
participant Bronsysteem
end box

activate Zorgviewer
Zorgverlener->Zorgviewer: ..vervolg bevragen bronsystemen zorgaanbieders..
loop
    Zorgviewer->Zorgviewer: voor iedere zorgaanbieder ([[Endpoint-UMCG.html Bronsysteem ontsluiting endpoint]])
    activate Zorgviewer
    Zorgviewer->Zorgviewer: formuleren documenten gegevensverzoek(request)
    Zorgviewer->Bron: gegevensverzoek\n""<bronsysteem-ontsluiting-base>/DocumentReference?patient=<patient_fhir_id>""
    activate Bron
    opt als token verlopen
        Bron->Bronsysteem : verkrijgen access token (dmv backend account)
    end opt
    Bron->Bronsysteem : gegevensverzoek met access token
    activate Bronsysteem
    Bronsysteem-->Bronsysteem: log request
    Bronsysteem->Bron: fhir resources (DocumentReference Bundle)
    deactivate Bronsysteem
    Bron-->Zorgviewer: Bundle met ""[[StructureDefinition-DocumentReference.html DocumentReference]]""
    deactivate Bron
    Zorgviewer->Zorgviewer: samenvoegen
    deactivate Zorgviewer
end
Zorgviewer->Zorgviewer: toon documenten lijst
Zorgviewer-->Zorgverlener
deactivate Zorgviewer
group wacht op gebruikers actie
...
end
Zorgverlener-->Zorgviewer: selecteer document
activate Zorgviewer
Zorgviewer->Bron: gegevensverzoek\n""<bronsysteem-ontsluiting-base>/Binary/<binary-id>""\nurl komt uit DocumentReference.content.attachement.url
note right Zorgviewer
    Stuur [[http://hl7.org/fhir/STU3/binary.html#rest Accept Header]]
    application/fhir+xml of application/fhir+json   
end note
activate Bron
opt als token verlopen
    Bron->Bronsysteem : verkrijgen access token (dmv backend account)
end opt
Bron->Bronsysteem : gegevensverzoek met access token
activate Bronsysteem
Bronsysteem-->Bronsysteem: log request
Bronsysteem->Bron: Binary
deactivate Bronsysteem
Bron-->Zorgviewer: Binary
deactivate Bron
Zorgviewer->Zorgviewer: toon document
Zorgviewer-->Zorgverlener
deactivate Zorgviewer

@enduml