@startuml
hide footbox
autonumber

title Opstarten Zorgviewer

actor Zorgverlener
box "EPD"
participant "Zorgviewer Host" as Host
participant Authenticatie
end box
participant Zorgviewer
participant "Zorgverlener Registry" as ZorgverlenerRegistry

Zorgverlener->Host: start EPD
Zorgverlener->Host: inloggen met lokale identiteit
Zorgverlener->Host: selecteer patient
Zorgverlener->Host: start Zorgviewer
Host->Zorgviewer: start met context\n""https://zorgviewer.nl""
note left Zorgviewer
 Context is iig zorgviewer-host-base, access token, gebruiker_fhir_id, patient_fhir_id
end note
Zorgviewer->Host: //SMART-on-FHIR handshake//

activate Zorgviewer
Zorgviewer->Authenticatie: check Identity //OAuth2//
Authenticatie-->Zorgviewer: gebruiker identity external identifier verkrijgen (e.g. AGB-Z of BIG-Nummer)
Zorgviewer->Host: Opvragen (lokale) gebruiker gegevens adhv gebruikerid\n""<zorgviewer-host-base>/Practitioner/<gebruiker_fhir_id>""
Host-->Zorgviewer: ""[[StructureDefinition-Practitioner.html Practitioner]]""
note right Zorgviewer
    obv AGB-Z of ziekenhuis van de gebruiker via signing van token
end note
Zorgviewer->Zorgviewer++: CHECK Autorisatie/whitelist om Zorgviewer te starten
destroy Zorgviewer

' ZORB-AB Implementatiehandleiding 2.8 paragraaf 4.7
Zorgviewer->ZorgverlenerRegistry: LATER: Opvragen (landelijke) gebruiker gegevens adhv external identifier\n""<zorg-ab-base>/Practitioner/?identifier=<agb-z>""\n""<zorg-ab-base>/PractitionerRole?practitioner.identifier=http://fhir.nl/fhir/NamingSystem/agb-z|<agb-z>""
ZorgverlenerRegistry-->Zorgviewer: ""[[StructureDefinition-Practitioner.html Practitioner]]"" volledige zorgverlener gegevens
note right Zorgviewer
  Inclusief specialisme, rollen e.d. zoals extern bekend met externe codering AGB/VEKTIZ
end note

Zorgviewer->Zorgviewer: LATER: kies rol (als meerdere, nodig voor de view)

Zorgviewer->Zorgviewer: Toon gebruiker gegevens

Zorgviewer->Host: opvragen patient gegevens (lokaal patientid)\n""<zorgviewer-host-base>/Patient/<patient_fhir_id>""
Host-->Zorgviewer: ""[[StructureDefinition-Patient.html Patient]]"" (onder andere BSN voor verdere raadplegingen)
Zorgviewer->Zorgviewer: Toon patient

Zorgviewer->Zorgviewer: **ga naar de Bepalen zorgaanbieders sequence**

deactivate Zorgviewer

@enduml