@startuml
hide footbox
autonumber

title Epic opstarten Zorgviewer

actor Zorgverlener
box "Epic EPD"
participant "Zorgviewer Host" as Host
participant Authenticatie
end box
participant Zorgviewer
participant "Zorgverlener Registry" as ZorgverlenerRegistry

Zorgverlener->Host: start EPD
Zorgverlener->Host: inloggen via Lokaal AD
Zorgverlener->Host: selecteer patient
Zorgverlener->Host: start Zorgviewer
Host->Zorgviewer: start met context (bronsysteem endpoint, gebruikerid, patientid)
Zorgviewer->Host: haal Authenticatie endpoints op

activate Zorgviewer
Zorgviewer->Authenticatie: check Identity (OAuth2)
Authenticatie-->Zorgviewer: raadpleger identity (external identifier gebruiker e.g. BIG-Nummer)
Zorgviewer->Host: OPTIONEEL opvragen volledige (lokale) gebruiker gegevens adhv gebruikerid
Zorgviewer->ZorgverlenerRegistry: details raadpleger (BIG-Nummer)
ZorgverlenerRegistry-->Zorgviewer: volledige gebruiker gegevens (inclusief specialisme, rollen e.d.) zoals extern bekend
Zorgviewer->Zorgviewer: LATER: kies rol (als meerdere, nodig voor de view)
Zorgviewer->Host: opvragen patient gegevens (lokaal patientid)
Host-->Zorgviewer: patient (onder andere BSN voor verdere raarplegingen)
Zorgviewer->Zorgviewer: toon gebruiker en patient
deactivate Zorgviewer

@enduml