@startuml
hide footbox
autonumber

actor Zorgverlener
box "EPD"
participant "Zorgviewer Host" as Host
participant Authenticatie
participant Bronsysteem
end box
participant Zorgviewer

activate Zorgviewer
Zorgverlener->Zorgviewer: ...
Zorgviewer->Zorgviewer: omzetten Host token naar algemeen token
Zorgviewer->"Bronsysteem ontsluiting": algemeen token
"Bronsysteem ontsluiting"->"Bronsysteem ontsluiting" : check algemeen token
"Bronsysteem ontsluiting"->Logging : log access
"Bronsysteem ontsluiting"->Bronsysteem : generiek zorgviewer back-end account
Bronsysteem->Logging : Logged zorggebruiker naam
deactivate Zorgviewer

@enduml