@startuml
hide footbox
autonumber

participant Zorgviewer
participant "EPD (via EPD ontsluiting)" as EPD
participant Toetser
participant Toestemming

activate Zorgviewer
Zorgviewer->Toetser:Gegevensverzoek
activate Toetser
Toetser->Toestemming: Verifieren Toestemming
Toestemming-->Toetser: Yes/no
Toetser->Toetser: Verifieren minimale dataset
Toetser->EPD:Gegevensverzoek
EPD-->Toetser: ZIBS
Toetser-->Zorgviewer: ZIBS
deactivate Toetser
Zorgviewer->Zorgviewer: Aggregate
Zorgviewer->Zorgviewer: Toon relevante geaggregeerde gegevens
deactivate Zorgviewer

@enduml