@startuml
hide footbox
autonumber

actor Zorgverlener
box "Eigen zorgaanbieder"
participant "Zorgviewer Host" as Host
participant Authenticatie
end box
participant Zorgviewer

Zorgverlener->Host: start EPD
Zorgverlener->Host: inloggen met lokale identiteit
Zorgverlener->Host: selecteer patient
Zorgverlener->Host: start Zorgviewer
Host->Zorgviewer: start met context dmv SMART-on-FHIR \n""https://app-tst.zorgviewer.nl/application/launch""
activate Zorgviewer
Zorgviewer<->Authenticatie: SMART-on-FHIR handshake
note left Zorgviewer
 Uit request: zorgviewer-host-base from URL

 token: {
  "access_token": "...",
  "id_token": "<JWT>",
  "patient": "<patient_fhir_id>",
  "practitioner": "<practitioner_fhir_id>"
  ... }

 access_token decoded: {
  "sub": "<practitioner_fhir_id>"
  ... }
end note
Zorgviewer->Host: opvragen gebruiker gegevens\n""<zorgviewer-host-base>/Practitioner/<practitioner_fhir_id>""
activate Host
Host-->Zorgviewer: ""[[StructureDefinition-Practitioner.html Practitioner]]""
note left Zorgviewer
 subject_role zit in Practitioner.qualification[system=SNOMED CT]
 subject_organization_id zit in Practitioner.meta[extension=source]
end note
deactivate Host
Zorgviewer->Zorgviewer: toon gebruiker gegevens

Zorgviewer->Host: opvragen patient gegevens\n""<zorgviewer-host-base>/Patient/<patient_fhir_id>""
activate Host
Host-->Zorgviewer: ""[[StructureDefinition-Patient.html Patient]]"" (onder andere BSN voor verdere raadplegingen)
deactivate Host
Zorgviewer->Zorgviewer: toon patient gegevens

Zorgviewer->Zorgviewer: **ga naar de Bepalen zorgaanbieders sequence**

deactivate Zorgviewer

@enduml