@startuml
hide footbox
autonumber

actor Zorgverlener
participant "*Eigen EPD" as EPD
participant Zorgviewer
participant Authenticatie
participant "*ProviderRegistry" as ProviderRegistry

Zorgverlener->EPD: start EPD
Zorgverlener->EPD: selecteer patient
Zorgverlener->EPD: start Zorgviewer
EPD->Zorgviewer: start met context

activate Zorgviewer
Zorgviewer->Authenticatie: check Identity
Authenticatie-->Zorgviewer: Raadpleger identity
Zorgviewer->ProviderRegistry: Attributen raadpleger adhv identity
ProviderRegistry-->Zorgviewer: Raadpleger+Bedrijfsrol(en)
Zorgviewer->Zorgviewer: kies rol
Zorgviewer->EPD: Bepalen patient
EPD-->Zorgviewer: Patient (+BSN)
deactivate Zorgviewer

@enduml