@startuml
hide footbox
autonumber

actor Zorgverlener
participant Zorgviewer
participant Behandelplan
box "Andere zorgaanbieder"
participant "Bronsysteem ontsluiting" as Bron
participant Bronsysteem
end box

activate Zorgviewer
Zorgverlener->Zorgviewer: ..vervolg bepalen zorgaanbieders..
Zorgviewer->Behandelplan: Bepalen minimale dataset\n""<behandelplan-base>/PlanDefinition?name=BgZ2017""
note right Zorgviewer
  Eerst hard-coded "BgZ2017" behandelplan.
  Later obv (hoofd)diagnose(zorgpad) of rol/specialisme gebruiker.
end note
activate Behandelplan
Behandelplan-->Zorgviewer: Behandelplan\n""[[StructureDefinition-PlanDefinition.html PlanDefinition]]""
deactivate Behandelplan
loop voor iedere zorgaanbieder
  Zorgviewer->Zorgviewer: [[Endpoint-UMCG.html Bronsysteem ontsluiting endpoint]]
  activate Zorgviewer
  Zorgviewer->Bron : verkrijg ""patient_fhir_id"" adhv BSN\n""<bronsysteem-ontsluiting-base>/Patient?identifier=<BSN>""
  activate Bron
  Bron->Bronsysteem : verkrijgen extern-access-token
  note left Bron
    auth_token bij access token request:
    { "iss": "...",
      "sub": "...",
      "exp": "...",
      ...
      (optioneel) "subject_organization": "UMCG",
      "subject_organization_id": "urn:oid:2.16.840.1.113883.2.4.3.8",
      ... }
  end note
  Bron->Bronsysteem : Patient request
  activate Bronsysteem
  Bronsysteem-->Bron : Patient resource
  deactivate Bronsysteem
  Bron-->Zorgviewer : ""[[StructureDefinition-Patient.html Patient]]""
  deactivate Bron
  loop gegevensverzoeken
    Zorgviewer->Zorgviewer: formuleren gegevensverzoek(request) adhv Behandelplan Data Requirements\n""PlanDefinition.action[0].output[].type""\nen ""PlanDefinition.action[0].output[].codeFilter""
    activate Zorgviewer
    Zorgviewer->Bron: gegevensverzoek\n""<bronsysteem-ontsluiting-base>/<resource>?subject=<patient_fhir_id>&<filter>""
    activate Bron
    Bron->Bron : verkrijgen extern-access-token
    Bron->Bronsysteem : gegevensverzoek (per zib) met generiek back-end account\ninclusief zorgviewer user organisatie tbv logging
    note right Bron
Organisatie adhv de AGB-Z of HL7 NL OID 
van de organisatie van de zorgviewer user.
    end note
    activate Bronsysteem
    Bronsysteem->Bron: fhir resources (Bundle) bij de zib
    deactivate Bronsysteem
    Bron->Bron: Toevoegen meta-tag voor deze bron\nadhv Patient.managingOrganization.display (en eventueel VEKTIS identifier)
    note right Bron
{ "meta": {
    "tag": [
      { "system": "http://hl7.nl/fhir/zorgviewer-ig/bronsysteem-zorgaanbieder",
        "code": "06020101",
        "display": "UMCG"
      } ] }
}
    end note
    Bron-->Zorgviewer: fhir resources (Bundle) bij de zib
    deactivate Bron
    deactivate Zorgviewer
    Zorgviewer->Zorgviewer: **TOEKOMST**: ontdubbelen en conflicten detectie
    note right of Zorgviewer
      Zorgviewer invulling van [[https://informatiestandaarden.nictiz.nl/wiki/BgZ:V1.0_BgZ_MSZ_Informatiestandaard BgZ]] 
      paragrafen 3.2.9.1 Ontdubbelen en 3.2.9.2 Duplicaatdetectie
    end note
  end
  deactivate Zorgviewer
end

Zorgviewer->Zorgviewer: toon gegevens
Zorgviewer-->Zorgverlener

@enduml