@startuml
hide footbox
autonumber

actor Zorgverlener
participant Zorgviewer
participant PatientIndex
participant Toestemming
participant Adressering

activate Zorgviewer
Zorgverlener->Zorgviewer: ..vervolg opstarten zorgviewer..
Zorgviewer->PatientIndex: Opvragen ontvankelijke zorgaanbieders (Open autorisatievraag adhv BSN)
note over PatientIndex: Afhankelijk van toestemming van patient\nvoor delen met de zorgverlener.
PatientIndex->Toestemming: Verifieren Toestemming
Toestemming-->PatientIndex: Yes/no
PatientIndex->Adressering: OPTIONEEL: get Endpoints voor zorgaanbieders (bronsysteem)
Adressering-->PatientIndex: Endpoints
PatientIndex-->Zorgviewer: Lijst ontvankelijke zorgaanbieders (incl Endpoints)
deactivate Zorgviewer

@enduml