on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Run-npm-on-Ubuntu:
    name: Run IG builder on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: java -version
      - run: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o publisher.jar
      - run: java -jar publisher.jar -ig ig.ini
